# Generated by Django 4.1.5 on 2023-01-18 12:29

import builtins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="province",
            options={"ordering": [builtins.id]},
        ),
        migrations.RenameField(
            model_name="province",
            old_name="modifled_on",
            new_name="modified_on",
        ),
    ]
