# Generated by Django 4.1.5 on 2023-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_alter_province_options_alter_province_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="province",
            name="is_obselete",
            field=models.BooleanField(default=False),
        ),
    ]
