# Generated by Django 4.1.5 on 2023-01-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0006_alter_district_province_municipalities"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Municipalities",
            new_name="Municipality",
        ),
    ]
