# Generated by Django 4.1.5 on 2023-01-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0007_rename_municipalities_municipality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="municipality",
            old_name="disrict",
            new_name="district",
        ),
    ]
