# Generated by Django 4.1.5 on 2023-01-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0008_rename_disrict_municipality_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="municipalities",
                to="geo.district",
            ),
        ),
    ]
