# Generated by Django 4.1.5 on 2023-01-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0009_alter_municipality_district"),
    ]

    operations = [
        migrations.RenameField(
            model_name="district",
            old_name="is_obselete",
            new_name="is_obsolete",
        ),
        migrations.RenameField(
            model_name="municipality",
            old_name="is_obselete",
            new_name="is_obsolete",
        ),
        migrations.RenameField(
            model_name="province",
            old_name="is_obselete",
            new_name="is_obsolete",
        ),
    ]
